jira:
  url: "https://your-domain.atlassian.net"
  email: "your-email@example.com"
  api_token: "your-api-token"

confluence:
  url: "https://your-domain.atlassian.net"
  email: "your-email@example.com"
  api_token: "your-api-token"
